### PR TITLE
加上我

### PR DESCRIPTION
**Pull request by Miku-chan39**

### CODE REVIEW

**Comment by hello1234316** [comment]
U can add by yourself
In index_unminify.html

**Comment by Miku-chan39** [comment]
~~u mean like this?~~

**Comment by hello1234316** [comment]
Like what

**Comment by Miku-chan39** [comment]
minify is a very bad idea
so i remove it

**Comment by hello1234316** [comment]
Ok
Thx

**Comment by hello1234316** [comment]
You can edit the index.html by yourself

**Comment by Miku-chan39** [comment]
huh?

**Comment by Miku-chan39** [comment]
Screenshot 2023-02-09 at 10 51 43 PM

**Comment by hello1234316** [comment]
I maan in the gh-pages  branch

**Comment by Miku-chan39** [comment]
just merge
it is a bad idea to commit on main

**Pull request closed without merging**
